name: marvel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  multiple_result: ^4.0.0
  flutter_modular: ^5.0.3
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.2
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^0.3.0

flutter:

  uses-material-design: true

  assets:
    - assets/mock.json
    - assets/icons/


  fonts:
    - family: Akshar
      fonts:
        - asset: assets/fonts/Akshar-Regular.ttf
          weight: 400
        - asset: assets/fonts/Akshar-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Akshar-Medium.ttf
          weight: 500
        - asset: assets/fonts/Akshar-Bold.ttf
          weight: 700
        - asset: assets/fonts/Akshar-VariableFont_wght.ttf
          weight: 800  
